"""Render tools/examples.py results into reference/recurring-examples.md."""
import json, subprocess, pathlib
r = json.loads(subprocess.check_output(["python3", "tools/examples.py", "--json"]))
a, o, t, rf, ex = r["arb"], r["own"], r["tax"], r["refi"], r["exit"]
m = lambda x: f"${x:,.0f}" if x >= 0 else f"-${-x:,.0f}"
L = []
w = L.append
w("# Recurring examples (canonical numbers)\n")
w("All figures are **assumptions for teaching**, generated by `tools/examples.py`. Do not change a number in a lesson without changing it here and re-running the script.\n")
w("## Example A: the Alder Street unit (arbitrage)\n")
w("A hypothetical two-bedroom, two-bath apartment (Unit 4B, 218 Alder Street) in a mid-size city we do not name, 10 minutes from a hospital campus and downtown. Sleeps 5. The student leases it from a small landlord who owns the four-unit building. The city is left unnamed on purpose: rules attach to an exact address, so lessons test the same unit against the official NYC and Los Angeles rules to show how the answer changes.\n")
w("| Assumption | Value |\n|---|---:|")
for k, v in [("Monthly rent", m(1950)), ("Average nightly rate (ADR)", m(205)), ("Occupancy", "70%"), ("Average stay", "3.0 nights"),
             ("Cleaning fee charged to guest", m(110)), ("Cleaner pay per turnover", m(95)), ("Airbnb single (host-only) service fee", "15.5% of nightly + cleaning"),
             ("Utilities + internet", "$260 / month"), ("Supplies", "$14 / stay"), ("STR liability insurance", "$1,300 / year"),
             ("Software", "$90 / month"), ("Repairs reserve", "$120 / month"), ("Permit / registration", "$250 / year")]:
    w(f"| {k} | {v} |")
w("\nOccupancy taxes are collected from guests and passed through, so they are left out of revenue and expenses here (lesson 3.3 covers them).\n")
def arb_table(title, s):
    w(f"### {title}\n")
    w(f"Booked nights {s['nights']}, stays {s['stays']}, ADR {m(s['adr'])}, occupancy {int(round(s['occupancy']*100))}%.\n")
    w("| Line | Annual |\n|---|---:|")
    w(f"| Nightly revenue | {m(s['nightly'])} |")
    w(f"| Cleaning fees collected | {m(s['cleaning_income'])} |")
    w(f"| **Gross booking revenue** | **{m(s['gross'])}** |")
    for k, v in s["lines"].items(): w(f"| {k} | -{m(v)} |")
    w(f"| **Total costs** | **-{m(s['total'])}** |")
    w(f"| **Net before income tax** | **{m(s['net'])}** ({m(s['net_month'])}/month) |")
    w(f"| Gross revenue as a multiple of annual rent | {s['rent_multiple']}x |\n")
arb_table("A1. Base case", a["base"])
arb_table("A2. Stress case (ADR down 12% to $180, occupancy 60%)", a["stress"])
w(f"### A3. Other what-ifs\n")
w(f"- Rent raised to $2,150: net {m(a['rent_up']['net'])} / year ({m(a['rent_up']['net_month'])}/month).")
w(f"- Full local manager at 20% of gross revenue: net {m(a['with_manager_20']['net'])} / year ({m(a['with_manager_20']['net_month'])}/month). Used in lesson 6.5.")
w(f"- Break-even occupancy at $205 ADR: {a['breakeven_occ']*100:.1f}%. At $180 ADR: {a['breakeven_occ_stress_adr']*100:.1f}%.\n")
w("### A4. Cash to start\n")
w("| Sunk setup cost (spent) | Amount |\n|---|---:|")
for k, v in a["startup"].items(): w(f"| {k} | {m(v)} |")
w(f"| **Total sunk setup** | **{m(a['startup_total'])}** |\n")
w("| Cash tied up (not spent) | Amount |\n|---|---:|")
for k, v in a["cash_tied"].items(): w(f"| {k} | {m(v)} |")
w(f"| **Total tied up** | **{m(a['cash_tied_total'])}** |\n")
w(f"Total cash needed on day one: **{m(a['cash_needed_total'])}**. Payback of sunk setup at the base-case net: {m(a['startup_total'])} / {m(a['base']['net_month'])} = **{a['payback_months']} months**. The landlord has offered a 24-month lease.\n")

w("## Example B: the Cedar Ridge house (ownership)\n")
w("A hypothetical three-bedroom, two-bath single-family house in a drive-to lake market about two hours from a metro area. Sleeps 8. No HOA. Asking price $399,000; the buyers' contract price is $385,000. Buyers: **Maya and Chris**, a two-earner household (combined W-2 income $185,000, credit scores around 740, $210,000 in liquid savings outside retirement accounts). They own their primary home: value $520,000, mortgage balance $260,000. They plan about 10 personal-use days a year.\n")
w("| Assumption | Value |\n|---|---:|")
for k, v in [("Purchase price", m(385000)), ("Down payment", "25%"), ("ADR", m(300)), ("Occupancy", "58%"), ("Average stay", "3.5 nights"),
             ("Cleaning fee charged / cleaner pay", "$175 / $150"), ("Platform fee", "15.5%"), ("Property tax", "$3,850 / year"),
             ("STR insurance", "$3,200 / year"), ("Utilities, internet, trash", "$450 / month"), ("On-call handyman / inspection retainer", "$150 / month"),
             ("Repairs + capital reserve", "5% + 5% of gross"), ("Furnishing budget", m(32000)), ("Closing costs", "3% of price, plus points"),
             ("DSCR quote (hypothetical)", "7.25%, 1 point, 30-yr fixed"), ("Conventional quote (hypothetical)", "6.875%, 0 points, 30-yr fixed")]:
    w(f"| {k} | {v} |")
def own_table(title, s):
    w(f"\n### {title}\n")
    w(f"Booked nights {s['nights']}, stays {s['stays']}, ADR {m(s['adr'])}, occupancy {int(round(s['occupancy']*100))}%.\n")
    w("| Line | Annual |\n|---|---:|")
    w(f"| **Gross booking revenue** | **{m(s['gross'])}** |")
    for k, v in s["lines"].items(): w(f"| {k} | -{m(v)} |")
    w(f"| **Operating costs** | **-{m(s['opex'])}** |")
    w(f"| **Net operating income (NOI)** | **{m(s['noi'])}** |")
own_table("B1. Operations, base case (owner self-manages with local cleaner and on-call handyman)", o["base"])
own_table("B2. Operations, weak case (ADR $265, occupancy 50%)", o["weak"])
own_table("B3. Operations with a full-service local co-host at 18%", o["with_cohost"])
w("\n### B4. Financing side by side\n")
w("| | DSCR quote | Conventional quote |\n|---|---:|---:|")
d, c = o["dscr"], o["conv"]
for label, key, fmt in [("Loan amount", "loan", m), ("Down payment", "down", m), ("Monthly P&I", "pi", m), ("Monthly PITIA", "pitia", m),
                        ("Annual debt service (P&I)", "debt_service_year", m), ("Closing costs incl. points", "closing", m),
                        ("Cash to close", "cash_to_close", m), ("Total cash in (with furnishing)", "total_cash_in", m),
                        ("Principal paid in year 1", "principal_paid_y1", m),
                        ("Annual cash flow, base case", "cash_flow_base", m), ("Annual cash flow, weak case", "cash_flow_weak", m),
                        ("Annual cash flow, base with 18% co-host", "cash_flow_with_cohost", m)]:
    w(f"| {label} | {fmt(d[key])} | {fmt(c[key])} |")
w(f"| Cash-on-cash, base case | {d['cash_on_cash_base']*100:.1f}% | {c['cash_on_cash_base']*100:.1f}% |")
w("\nReserves are not in these totals. A lender may require months of PITIA in reserve on top of cash to close (lesson 0.3 and PA.6).\n")
w("### B5. Three ways to compute a coverage ratio on the DSCR quote\n")
w(f"- Gross booking revenue / annual PITIA: {o['gross_dscr_base']} (weak case {o['gross_dscr_weak']}).")
w(f"- Gross revenue discounted 20% / annual PITIA: {o['haircut_dscr_base']}.")
w(f"- NOI before property tax and insurance / annual PITIA: {o['noi_dscr_base']}.")
w("\nSame house, three different answers. The lender's written definition decides which one counts. The teaching point: a lender ratio above 1.0 does not mean positive cash flow for the owner.\n")
w("### B6. Depreciation illustration (CPA must confirm every input)\n")
w("| Item | Amount |\n|---|---:|")
for k, v in [("Depreciable basis incl. $6,000 capitalized closing costs", t["basis"]), ("Land allocation (20%, assumption)", t["land"]),
             ("Building", t["building"]), ("Straight-line per full year, 39-year (nonresidential / transient use)", t["sl_39"]),
             ("Straight-line per full year, 27.5-year (residential rental)", t["sl_275"]),
             ("Cost-seg reclass to 5/7/15-year property (22% of building, assumption)", t["short_life"]),
             ("Furnishings (5-year property)", t["furnishing"]), ("Year-1 bonus depreciation IF eligible at 100%", t["bonus_year1"]),
             ("Remaining building, per full year at 39 years", t["remaining_39_full_year"])]:
    w(f"| {k} | {m(v)} |")
w(f"\nIllustrative only: at an assumed 32% marginal rate, year-1 deductions of about {m(t['bonus_year1'] + t['remaining_39_full_year'])} *could* reduce tax by about {m(t['illustrative_tax_effect'])}, **only if** the losses are usable against other income (material participation, average-stay tests, and loss limits). If the activity is passive, the loss may be suspended and carried forward. First-year straight-line uses a full year here for simplicity; the real first year depends on the placed-in-service month and convention.\n")
w("### B7. Refinance at the end of year 2 (DSCR loan, value grows 3% a year, assumption)\n")
for k, v in [("Value", m(rf["value_y2"])), ("Loan balance", m(rf["balance_y2"])), ("New loan at 75% LTV", m(rf["new_loan_75"])),
             ("Refinance costs (2.5%)", m(rf["refi_cost"])), ("Cash out after payoff and costs", m(rf["cash_out"])),
             ("New P&I at 7.0%", m(rf["new_pi"]) + "/month"), ("Annual cash flow after refi, base", m(rf["cash_flow_after"])),
             ("Annual cash flow after refi, weak", m(rf["cash_flow_after_weak"]))]:
    w(f"- {k}: {v}")
w("\n### B8. Sale at the end of year 5 (before income tax)\n")
for k, v in [("Value", ex["value_y5"]), ("Loan balance (original DSCR loan, no refi)", ex["balance_y5"]), ("Selling costs at 7%", ex["sale_costs_7pct"]),
             ("Net proceeds before tax", ex["net_before_tax"])]:
    w(f"- {k}: {m(v)}")
w("\nTax on the sale (including recapture of depreciation taken) is not in this figure. Lesson OP.12 treats it as a CPA input.\n")
pathlib.Path("reference").mkdir(exist_ok=True)
pathlib.Path("reference/recurring-examples.md").write_text("\n".join(L))
print("ok", len(L))
